### ISSUE TITLE
[Urgent] Soft Occlusion not working as planned on 5.4.1 Meta Fork and v66-v67 HorizonOS

### ISSUE THREAD

**Issue by Nickauhla** [oculus-samples/Unreal-OcclusionSample#4]
Hello,

Since 2 weeks, I have a very annoying problem with soft occlusion.
I think that the hand removal system is interfering in a non desired way with the soft collision system:
- I've opened the OcclusionSample with UE 5.4.1 Meta Fork - v66 MetaXR plugin as it is the last version available and v67 OS on Quest Headsets.
- No collision and Hard collision seems to behave as planned.
- When enabling soft collision, I have part of my meshes/sprites that are hidden in a weird way.
If I move my hand in the bottom half of my passthrough fov, it behaves like my hand is masking the 3D object. I've managed doing so to have a sort of "masking shadow" the form of my hand masking the 3D object.
Enabling or disabling the "remove hand" feature does have an impact but doesn't solve the weird masking issue.

How I put my hands:
![Mon premier tableau - Cadre 1](https://github.com/user-attachments/assets/e8df14dd-afd8-4a33-9e80-b0aa1b5ce4c3)

An example of the result. In this one, my hand is about 1 m ahead of the HMD, I'm not masking directly the depth camera.
Plus, my hands is below the hidden sprite, so it should not be hidden at all.
![OculusScreenshot1721222156](https://github.com/user-attachments/assets/8385e238-3bce-4b35-800f-6f372270147c)

**Comment by MartinSherburn** [comment]
Thanks @Nickauhla for the report, there is a known regression in v67 Meta Quest Link that unfortunately we caught too late to fix. Your report sounds very similar to this issue. Please can you confirm this issue only occurs when using Meta Quest Link and not when running natively on your Quest device? If so there is a fix for this issue coming in v68.

**Comment by Nickauhla** [comment]
I think so. I've tried an old build that does not present the problem.
Unfortunatly, I can't build the current project in mobile anymore, so i can't confirm but I think that's the case.

Do you have any idea when the v68 will be released?

**Comment by MartinSherburn** [comment]
> Do you have any idea when the v68 will be released?

The release cadence is usually once per month but I can't give you an exact date.

> Now, i don't have occlusion anymore when activating "Soft Occlusion", but I get this error in the console:

Currently we only support DX11 RHI. Please try changing the project settings to DX11 (instead of Vulkan or DX12)

**Comment by Nickauhla** [comment]
Ok.

I can confirm that switching back to DX11 I get the same behaviour than in my previous message.

**Comment by MartinSherburn** [comment]
v68 is released now. I'm going to close this issue. Please let us know if the issue persists.
