### ISSUE TITLE
Depth Occlusion issue with Level Travel

### ISSUE THREAD

**Issue by Junnn424** [oculus-samples/Unreal-OcclusionSample#5]
Hi all, Hi @MartinSherburn,
Thank you for the response on[ this page](https://github.com/oculus-samples/Unreal-MRUtilityKitSample/issues/2), moving my issue here and added some more details:
We found that there are 2 behaviors with Depth Occlusion after level travel (or reopen the same map), 
1. If we have occlusion ON (no matter it's hard or soft occlusion):
Depth Occlusion works perfect at the first level, but once we travel to another map or use "Open level' to open the same map again, it starts to render differently on each eye (see pic reference below)
recording: https://youtu.be/by_Wx87PESo
![2024-08-06T02-52-49 395Z](https://github.com/user-attachments/assets/e8bff472-f48c-44a5-b6b9-904d90cdd4f6)

2. If we turn occlusion ON and then turn it OFF before reopen the level, the Occlusion renders the same on both eyes but the position of it is offset from the physical object:
https://youtu.be/jOAhBRKNaAQ
![image](https://github.com/user-attachments/assets/81b48ddf-621f-40de-99e3-0438836e90d0)

More details:
At game start, I start at "Map_Lobby_01" using BP_VRPawn, the BP_VRPawn already has a passthrough layer (reconstructed/ underlay) attach to its camera. When I press "Oculus X", it cycles through "Hard occlusion"/ "Soft occlusion"/ "No occlusion" . Then, I use "Open Map_Lobby_01" to reopen the same map again. In the first recording I was in Vanilla Unreal 5.4, so there was no soft occlusion.
![image](https://github.com/user-attachments/assets/18014f19-c254-4683-b51c-eb06589c1e6a)
![image](https://github.com/user-attachments/assets/d09c1257-e7db-4749-8106-46c5a882bb40)

Things I tried:
- Switch to oculus branch UE and tested soft occlusion, soft occlusion works, depth issue after level travel persists:
https://youtu.be/Kofk7k68qJ8
- Remove the passthrough layer on pawn and add it at begin play same as in occlusion sample, as show below, the problem persists:
![image](https://github.com/user-attachments/assets/1ec79fb7-916b-4701-9916-5c51b712070a)

**Comment by MartinSherburn** [comment]
Thanks for the report and detailed information @Junnn424, I'm going to try replicate this in the OcclusionSample and see if we can figure out what is going on.

**Comment by MartinSherburn** [comment]
@Junnn424 I've tried to replicate what you described in the Occlusion sample. What I did is that I added a new input action so that when the B or Y button is pressed it calls Open Level to reload the current level. When I did this I wasn't able to reproduce the problems you described (I'm using the Meta fork of the engine). Cycling through the occlusion modes and reloading the level doesn't cause any issues. Here is what I added to the level BP:

![image](https://github.com/user-attachments/assets/d02294c8-389a-4fad-a850-e1304753d67b)

I'm wondering if there is anything else specific to your project that could be causing this issue. If you are able to reproduce the issue in the Occlusion sample that would be really help to debug this.

**Comment by Junnn424** [comment]
hi @MartinSherburn 
Thank you for getting back to me and share your testing!
I did found the reason at the end, please try add "Reset orientation and Position" at begin play in Occlusion sample project, and I believe you would see the same behavior.
![image](https://github.com/user-attachments/assets/d04149bb-c4e1-4eed-a656-8c6018cbc6a4)

**Comment by MartinSherburn** [comment]
@Junnn424 great, I was able to reproduce it with the "Reset orientation and Position" node!

I found the problem and have a fix for this. It will be in v71. But in the mean time you can apply the patch locally to unblock yourself. The changes are fairly small, see below:

```
diff --git a/OculusXR/Source/OculusXRHMD/Private/OculusXRHMD.cpp b/OculusXR/Source/OculusXRHMD/Private/OculusXRHMD.cpp
--- a/OculusXR/Source/OculusXRHMD/Private/OculusXRHMD.cpp
+++ b/OculusXR/Source/OculusXRHMD/Private/OculusXRHMD.cpp
@@ -4417,6 +4417,7 @@
 
 		SwapchainIndex = DepthFrameDesc[0].SwapchainIndex;
 		const float WorldToMetersScale = Frame_RenderThread->WorldToMetersScale;
+		const auto InverseBaseOrientation = Settings_RenderThread->BaseOrientation.Inverse();
 
 		if (DepthViewProj != nullptr)
 		{
@@ -4428,7 +4429,7 @@
 				DepthFrustum.zFar = DepthFrameDesc[i].FarZ * WorldToMetersScale;
 				FMatrix DepthProjectionMatrix = ToFMatrix(ovrpMatrix4f_Projection(DepthFrustum, true));
 
-				auto DepthOrientation = Frame_RenderThread->TrackingToWorld.GetRotation() * ToFQuat(DepthFrameDesc[i].CreatePose.Orientation);
+				auto DepthOrientation = Frame_RenderThread->TrackingToWorld.GetRotation() * InverseBaseOrientation * ToFQuat(DepthFrameDesc[i].CreatePose.Orientation);
 
 				// NOTE: This matrix is the same as applied in SetupViewFrustum in SceneView.cpp
 				auto ViewMatrix = DepthOrientation.Inverse().ToMatrix() * FMatrix(FPlane(0, 0, 1, 0), FPlane(1, 0, 0, 0), FPlane(0, 1, 0, 0), FPlane(0, 0, 0, 1));
@@ -4488,7 +4489,7 @@
 
 			// 2. The headset may have moved in between capturing the environment depth and rendering the frame. We
 			//    can only account for rotation of the headset, not translation.
-			auto DepthOrientation = ToFQuat(DepthFrameDesc[i].CreatePose.Orientation);
+			auto DepthOrientation = InverseBaseOrientation * ToFQuat(DepthFrameDesc[i].CreatePose.Orientation);
 			if (!DepthOrientation.IsNormalized())
 			{
 				UE_LOG(LogHMD, Error, TEXT("DepthOrientation is not normalized %f %f %f %f"), DepthOrientation.X, DepthOrientation.Y, DepthOrientation.Z, DepthOrientation.W);
```

I hope that helps.

**Comment by Junnn424** [comment]
Thank you @MartinSherburn , it works just fine with reset orientation and position now!
